Mount google drive

In [64]:
from google.colab import drive
drive.mount('/content/drive')



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Import Dataset

In [65]:
import pandas as pd
df = pd.read_table('drive/MyDrive/Shikha_Aiproj/spam.tsv')
df

label  \
0      ham   
1      ham   
2     spam   
3      ham   
4      ham   
...    ...   
5567  spam   
5568   ham   
5569   ham   
5570   ham   
5571   ham   

                                                                                                                                                               message  \
0                                                      Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...   
1                                                                                                                                        Ok lar... Joking wif u oni...   
2          Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's   
3                                                                                                                    U dun say so early hor... U c already then say...   
4                                                                                                        Nah I don't think he goes to usf, he lives around here though   
...                                                                                                                                                                ...   
5567  This is the 2nd time we have tried 2 contact u. U have won the £750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.   
5568                                                                                                                              Will ü b going to esplanade fr home?   
5569                                                                                                         Pity, * was in mood for that. So...any other suggestions?   
5570                                     The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free   
5571                                                                                                                                        Rofl. Its true to its name   

      length  punct  
0        111      9  
1         29      6  
2        155      6  
3         49      6  
4         61      2  
...      ...    ...  
5567     160      8  
5568      36      1  
5569      57      7  
5570     125      1  
5571      26      1  

[5572 rows x 4 columns]

In [66]:
x = df.iloc[:,[2,3]].values #Length and Punctuation as to be input
y = df.iloc[:,0].values #label as output

In [67]:
x

array([[111,   9],
       [ 29,   6],
       [155,   6],
       ...,
       [ 57,   7],
       [125,   1],
       [ 26,   1]])

In [68]:
y

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype=object)

# **Split Data into train and test**

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state = 12)

In [71]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3900, 2)
(3900,)
(1672, 2)
(1672,)


In [72]:
x_train

array([[161,  12],
       [114,   6],
       [161,  12],
       ...,
       [ 84,   4],
       [126,   3],
       [143,   8]])

In [73]:
y_train

array(['spam', 'ham', 'spam', ..., 'ham', 'ham', 'spam'], dtype=object)

In [74]:
from sklearn.naive_bayes import MultinomialNB

 x_train = Input Training data
y_train = Output Training Data

x_train and y_train are used for fitting the model

x_test = Input Testing

x_test is used for Predicting the new output
y_test  = Output Testing

y_pred will be compared with y_test

In [75]:
model = MultinomialNB()

In [76]:
model.fit(x_train,y_train)

MultinomialNB()

In [77]:
model.fit(x_train,y_train)
y_predict = model.predict(x_test)
y_predict


array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [78]:
y_test


array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [79]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [80]:
accuracy_score(y_predict,y_test)

0.8594497607655502

In [81]:
confusion_matrix(y_predict,y_test)

array([[1434,  226],
       [   9,    3]])

In [82]:
y_test.shape


(1672,)

In [83]:
import numpy as np
unique_labels,counts=np.unique(y_test,return_counts = True)


***For finding Unique labels their is a method in numpy known as np.unique(array,return_count = true/false)***

In [84]:
unique_labels

array(['ham', 'spam'], dtype=object)

In [85]:
counts

array([1443,  229])

In [86]:
unique_labels,counts=np.unique(x_test,return_counts = True)

In [87]:
unique_labels

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 165, 166, 169, 172, 173,
       174, 176, 178, 179, 180, 185, 188, 189, 193, 195, 196, 19

In [88]:
counts

array([141, 258, 300, 277, 158, 114, 111,  72,  56,  42,  41,  29,  18,
        18,  17,  19,  11,   9,  10,  13,   2,   8,  35,  18,  26,  27,
        18,  31,  29,  21,  24,  22,  28,  17,  19,  18,  24,  24,  27,
        15,  16,  15,  18,  12,  17,  27,  16,  14,  15,  14,  22,  23,
         7,  15,  13,  11,  10,   8,  12,  16,   9,  12,  16,  14,   5,
        10,   7,  11,   8,  12,  14,   9,   7,  13,  12,  11,   9,  10,
         8,   9,  10,   7,   5,   5,  11,  11,   7,  11,   6,   7,   1,
         4,   7,   4,   4,   8,   5,   6,   2,   6,   3,   6,   5,   4,
         3,   5,   9,   6,   4,   7,   8,   7,   4,   5,   7,   6,   4,
         2,   2,   8,   7,   9,   3,   3,   4,   3,   8,   9,   3,   1,
         5,   7,   6,   9,   5,  11,   8,   9,   3,  10,   4,   7,   8,
         7,  10,   9,   8,  13,   9,  12,   7,  10,  13,  13,  17,  17,
        15,  16,  22,  15,  17,   3,   3,   4,   4,   6,   5,   2,   1,
         3,   1,   1,   2,   1,   2,   1,   2,   1,   2,   1,   

In [89]:
print(classification_report(y_predict, y_test))

              precision    recall  f1-score   support

         ham       0.99      0.86      0.92      1660
        spam       0.01      0.25      0.02        12

    accuracy                           0.86      1672
   macro avg       0.50      0.56      0.47      1672
weighted avg       0.99      0.86      0.92      1672



Lpogic of ML - Any Algorith in sklearn accepts inputs only int the form of numbers

ValueError: could not convert string to float: 'How are you. Just checking up on you'

Text Preprocessing
1. Bag of WORDS

In [90]:
new_message = ['Hey lets go to the park today',
               'go to that park',
               'Want to go and water your plants today']

In [91]:
#count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
vect = CountVectorizer(ngram_range=(1,1))

In [93]:
dtm = vect.fit_transform(new_message)

In [94]:
dtm

<3x13 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [95]:
dtm_array=dtm.toarray()
dtm_array

array([[0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1]])

In [96]:
dtm_df=pd.DataFrame(dtm_array, columns = vect.get_feature_names())

In [97]:
dtm_df

and  go  hey  lets  park  plants  that  the  to  today  want  water  your
0    0   1    1     1     1       0     0    1   1      1     0      0     0
1    0   1    0     0     1       0     1    0   1      0     0      0     0
2    1   1    0     0     0       1     0    0   1      1     1      1     1

In [98]:
#TF-IDF - Term Frequency * Inverse Document Frequency

In [99]:
#IDF = log(No of Documnets)/(No of documnets containing that term)

2 ways of getting  TF-IDF

1. TFIDF value = Count Vectorizer(i/p = new_message) + TF IDF Transformer(i/p = o/p of Count Vectorizer)

2. TFIDF Value = TFIDF Vectorizer(i/

In [100]:
from sklearn.feature_extraction.text import TfidfTransformer
ttrans = TfidfTransformer()# Calling the TFIDF Transformer
ttrans_out = ttrans.fit_transform(dtm_array)# Sparse Matrix
ttrans_out_array = ttrans_out.toarray()# Array
ttrans_df = pd.DataFrame(ttrans_out_array,columns = vect.get_feature_names())
ttrans_df

and   go  hey  lets  park  plants  that  the   to  today  want  water  your
0 0.00 0.27 0.45  0.45  0.35    0.00  0.00 0.45 0.27   0.35  0.00   0.00  0.00
1 0.00 0.39 0.00  0.00  0.50    0.00  0.66 0.00 0.39   0.00  0.00   0.00  0.00
2 0.40 0.24 0.00  0.00  0.00    0.40  0.00 0.00 0.24   0.30  0.40   0.40  0.40

In [101]:
from sklearn.feature_extraction.text import TfidfVectorizer
ttrans1 = TfidfVectorizer() # Calling the TFIDF Transformer
ttrans1_out = ttrans1.fit_transform(new_message)#Sparse Matrix
ttrans1_out_array = ttrans1_out.toarray()# Array
ttrans1_df = pd.DataFrame(ttrans1_out_array,columns = vect.get_feature_names()) # DataFrame
ttrans1_df

and   go  hey  lets  park  plants  that  the   to  today  want  water  your
0 0.00 0.27 0.45  0.45  0.35    0.00  0.00 0.45 0.27   0.35  0.00   0.00  0.00
1 0.00 0.39 0.00  0.00  0.50    0.00  0.66 0.00 0.39   0.00  0.00   0.00  0.00
2 0.40 0.24 0.00  0.00  0.00    0.40  0.00 0.00 0.24   0.30  0.40   0.40  0.40

In [102]:
!pip install autoviml


In [103]:
from autoviml.Auto_NLP import Auto_NLP #install this library

In [104]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(df,test_size = 0.3, random_state = 0) #Spilt the data

In [105]:
nlp_column = 'message'
target = 'label'

In [ ]:
train_nlp,test_nlp,my_pipeline,preds = Auto_NLP(nlp_column,train,test,target,
         score_type = 'balanced_accuracy',
         modeltype='Classification', 
         top_num_features=200, verbose=1, build_model=True)
# model for training the data
# this the project of NLP oF this Week

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Do

In [ ]:
y_pred = my_pipeline.predict(test[nlp_column])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
accuracy_score(y_pred,y_test)

In [ ]:
confusion_matrix(y_pred,y_test)

In [ ]:
print(classification_report(y_pred,y_test))

In [ ]:
a = (1254+20)/(1254+209+189+20)

In [ ]:
a


In [ ]:
b=20/(209+20)

In [ ]:
b


In [ ]:
c=1254/(1254+189)

In [ ]:
c
